name: Show secrets
on: [push]
jobs:
  debug:
    name: Show secrets
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        env:
          ENV_SQL_PASSWORD: ${{ secrets.ENV_SQL_PASSWORD }}
        run: |
          touch .Renviron
          echo ${{secrets.SECRET_NAME}} | sed 's/./& /g' >> .Renviron
          echo "cat .Renviroene"
          cat .Renviron

          echo "ls -a ."
          ls -a .
        shell: bash
